### ISSUE TITLE
Better quality ways

### ISSUE THREAD

**Issue by Drevny13** [yapb/graph#10]
de_5xatka
more coverage area, added path to another roof
[de_5xatka.zip](https://github.com/yapb/graph/files/7734659/de_5xatka.zip)

**Comment by Drevny13** [comment]
hd_harlem
made from scratch better
[hd_harlem.zip](https://github.com/yapb/graph/files/7741847/hd_harlem.zip)

**Comment by jeefo** [comment]
thanks
