### ISSUE TITLE
Add bots in this map(miragesky) please ,Thanks a lot.

### ISSUE THREAD

**Issue by jlinwork** [yapb/graph#11]
The map name : miragesky
[miragesky.zip](https://github.com/yapb/graph/files/7746106/miragesky.zip)

**Comment by Drevny13** [comment]
done 
[miragesky.zip](https://github.com/yapb/graph/files/7747257/miragesky.zip)
add to 
cstrike\addons\yapb\data\graph

also same map in winter style
[css_miragewinter_go.zip](https://github.com/yapb/graph/files/7747314/css_miragewinter_go.zip)

**Comment by jeefo** [comment]
thanks
