### ISSUE TITLE
Решена ли проблема с невозможностью загрузки graph файла в базу?

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/graph#12]
@jeefo 
Overitab или он же Drevny13 писал мне в дискорд что он не мог выгрузить граф через yb g upload, в консоли пишет что всё норм, но сам файл не появляется в базе.

Он сказал что писал вам в Telegram по этому поводу

**Comment by jeefo** [comment]
привет. да, есть косяк. поправлю на днях

**Comment by jeefo** [comment]
@Vladislav4KZ проверяте

**Comment by Vladislav4KZ** [comment]
> @Vladislav4KZ проверяте

Загрузил его graph. Да, работает
