### ISSUE TITLE
de_junglebase.pwf

### ISSUE THREAD

**Issue by commandcobra7** [yapb/graph#22]

**Comment by PRinceBhai** [comment]
Searching for de_junglebase give me a result of de_sampa. So I can't find de_junglebase anywhere, if you have then please either link it or upload it with it's dependencies.

**Comment by commandcobra7** [comment]
> Searching for de_junglebase give me a result of de_sampa. So I can't find de_junglebase anywhere, if you have then please either link it or upload it with it's dependencies.

If you can't find the map, the download link is below.

https://www.17buddies.rocks/17b2/View/Map/92290/de_junglebase.html

**Comment by PRinceBhai** [comment]
Done.
