### ISSUE TITLE
Some Existing Graphs are poorly done or ported.

### ISSUE THREAD

**Issue by PRinceBhai** [yapb/graph#26]
@jeefo Can you check de_rotterdam? The graph that is on the repo is broken or the graph is from an other version of the map.
I've redone the Graph from scratch but can't upload it.

This is also a case with more maps that I've forgotten to mention.

**Comment by jeefo** [comment]
You can create a PR with new graph)

**Comment by PRinceBhai** [comment]
> You can create a PR with new graph)

Umm, I don't understand what you mean by "PR"?

**Comment by jeefo** [comment]
Pull reqeuest? you already done right! thank you
