### ISSUE TITLE
Waypoint request

### ISSUE THREAD

**Issue by dimaspaf14** [yapb/graph#33]
Here:
[~De_dust_go~](https://gamebanana.com/mods/83894) Already [done](https://github.com/yapb/graph/blob/master/graph/de_dust_go.graph) but idk who
[~Cs_italy_go~](https://gamebanana.com/mods/92095) [Done](https://github.com/yapb/graph/commit/e67376597305ac4ab6bcc2231429d64e9d3171f1)  by Drevny13
[~De_dust_pena~](https://gamebanana.com/mods/83649)  [Done](https://github.com/yapb/graph/commit/fcb924d75ccc7be73d011e50f2707555f3907046) by Drevny13
[~De_dust2_cs2d~](https://gamebanana.com/mods/328484) Already [done](https://github.com/yapb/graph/blob/master/graph/de_dust2_cs2d.graph) by Drevny13
[~Cs_assault_go v7.0~](https://gamebanana.com/mods/91651) [Done](https://github.com/yapb/graph/commit/33c087634f5aa0d1cb17f41e06bb4f06a89335c9) by Drevny13 
[~De_dust2_go v6.0~](https://gamebanana.com/mods/83727) [Done](https://github.com/yapb/graph/commit/72dae33a29b158e3156c6e1f605b1f62d1fd2d1b) by Drevny13
[~De_dust2_go 2x2a~](https://gamebanana.com/mods/338296) [Done](https://github.com/yapb/graph/blob/master/graph/de_dust2_go_2x2a.graph) by @Drevny13
[~De_dust2_go 2x2b~](https://gamebanana.com/mods/339633) [Done](https://github.com/yapb/graph/commit/6850449fa86eb9f351fefdc2b6666b146158c284)  by  Drevny13

A bit too much, hehe...

**Comment by dimaspaf14** [comment]
~Waypoint request completed: 37,5% (3/17/22)~

~Waypoint request completed: 62,5% (3/19/22)~

Waypoint completed 100%, Thanks for @Drevny13 for working all the graph
(3/20/22)

**Comment by Drevny13** [comment]
done

**Comment by dimaspaf14** [comment]
> done

Thank you so much @Drevny13 
I may update my maps in a few weeks, so in case if the graph need to update ill contact you @drevny13 at gamebanana ok?

**Comment by dimaspaf14** [comment]
I forgor to close
