### ISSUE TITLE
Wrong de_rotterdam.graph

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/graph#40]
@PRinceBhai What version of the map did you make the new graph for? I used the previous graph by `*dur5t*` and it fit this map.

When I put your "fixed" graph, it turned out that the nodes are outside the map.

**Comment by Vladislav4KZ** [comment]
I found out that the graph you made belongs to the map de_rotterdam2. But not de_rotterdam.

Make sure your map has the correct name, because I googled and found the same versions of the de_rotterdam map.

**Comment by Vladislav4KZ** [comment]
I found out that the graph you made belongs to the map de_rotterdam2. But not de_rotterdam.

Make sure your map has the correct name, because I googled and found the same versions of the de_rotterdam map.

**Comment by Vladislav4KZ** [comment]
So, the graph which is located in database made for this map: https://www.17buddies.rocks/17b2/View/Map/329/de_rotterdam.html

The graph you made refers to the map: https://www.17buddies.rocks/17b2/View/Map/5732/de_rotterdam2.html

But, the database also has a graph for this map. If you think your graph is better, you can make a pull request with a different graph file name (de_rotterdam2.graph)

**Comment by PRinceBhai** [comment]
Yeah, I just checked the maps and you're right. I don't know where I got the copy of the map I have from. I'll remove my graph. If it hasn't been done yet.  Edit : Updated both of the graphs.
