### ISSUE TITLE
Please add the following map waypoints

### ISSUE THREAD

**Issue by ghost** [yapb/graph#42]
de_dust2j
cvt_dust
cvt_dust0j
cvt_dust2s
cvt_dust2006
cvt_dust2x
cvt_house
de_d_u_s_t
de_dust2_otg
de_dust4u
de_dust69er
de_aztec2003
de_aztec2003x
de_dustb_beta
de_dust_b
de_aztec_ice
de_extrain
de_dust_quin
de_bashkortostan
de_dust2_2008
de_dust2_08
de_dust_remake
de_train_2006
de_kzdust
de_cs_dust2
de_aztec2006
de_aztec2007v2
de_kefar
de_morning
de_afghan_r
de_dust_versa
de_dust2_kwf
de_dust2_versa
de_snowden_kyz
de_aztec_1337
de_dust2_1337_pr_cz
de_dust2_1337_cz
de_dust2_extended_PR_cz
de_dust2_extended_cz
de_castle_lin
de_reborn
de_dust828
de_dust8
de_dust_2006
de_epicentar
de_newdust2_2010
de_target_dust2_b3
de_dust_wntdm
de_dust_thailand
de_dustbr
de_dust4e
de_niroon
de_lostcars
de_driver2k
de_dust_boka2_cz
de_dust_1967_cz
de_dust2_phenix_beta2
de_mixgp_dd
de_dust_plus
de_dust2_toon
de_dust2_x
de_dust2002b
de_dustmust
de_dust2_thera_b5
cs_dust2_suncsm
de_aztec_suncsm
de_dust_suncsm
de_inferno_suncsm
de_sunny_suncsm
cs_assault_magmas
cs_dust2_magmas
de_aztec_magmas
de_dust_magmas
de_dust2_magmas
de_inferno_magmas
de_noel-d2_magmas
de_noel_dust-magmas_b1
de_sunny_magmas
de_dust2_santorini_b2
de_aztec2014
de_dustec_final
de_dust2_obliv
de_nuke_santorini_b2
de_czl_freight
de_guerrilla
de_dust2002_spring_b1

**Comment by Vladislav4KZ** [comment]
It would be better to provide links to maps, since Google can't find some maps by name.

**Comment by ghost** [comment]
I uploaded the map to HTTP
http://cs15.noip.cn:29010/

**Comment by PRinceBhai** [comment]
@Vladislav4KZ I've made and uploaded every map from this list except these, that I could not find :

I've also written the issue I encountered, while searching for them.

de_dust2j
cvt_dust
cvt_dust0j
cvt_house
de_d_u_s_t
de_aztec2003		       : Could only find this on ds-servers.com but it seems corrupted.
de_dustb_beta
de_dust_quin
de_dust2_08			: It is on 17buddies but the site seems to be down for me.
de_dust_remake		: Could only find one for CS:S
de_aztec2007v2		: It is on 17buddies but the site seems to be down for me.
de_morning
de_dust_versa		        : It is on 17buddies but the site seems to be down for me.
de_dust2_kwf		        : It is on 17buddies but the site seems to be down for me.
de_dust2_versa		: It is on 17buddies but the site seems to be down for me.
de_reborn
de_dust828			: It is on 17buddies but the site seems to be down for me.
de_dust8			        : It is on 17buddies but the site seems to be down for me.
de_dust_2006		        : It is on 17buddies but the site seems to be down for me.
de_newdust2_2010	        : It is on 17buddies but the site seems to be down for me.
de_target_dust2_b3
de_dustbr			: It is on 17buddies but the site seems to be down for me.
de_dust4e
de_driver2k			: It is on 17buddies but the site seems to be down for me.
de_dust_plus		        : It is on 17buddies but the site seems to be down for me.
cs_dust2_suncsm		: It is on 17buddies but the site seems to be down for me.
de_sunny_suncsm		: It is on 17buddies but the site seems to be down for me.
cs_assault_magmas	        : It is on 17buddies but the site seems to be down for me.
cs_dust2_magmas		: It is on 17buddies but the site seems to be down for me.
de_dust_magmas
de_inferno_magmas
de_noel-d2_magmas	: It is on 17buddies but the site seems to be down for me.
de_sunny_magmas		: It is on file.cs-best.org.ua but the site is always busy.

If you can find some of these maps then please link the downloads here, I'll make the waypoints for them as well, if not then you can close this. 👍

**Comment by Vladislav4KZ** [comment]
@PRinceBhai I saw these maps at the address below. Looks like it's a fastdl. 

> I uploaded the map to HTTP
> http://cs15.noip.cn:29010/

17buddies doesn't work for me either.
Google found some maps, but they were in mappacks and not a zip file with the single map.


@Jockey731 is this your request? Can you give normal links to maps with all the necessary resources so as not to download one file at a time and guess what additional files you need to download for the map.

The 17Ims (17's Buddies Integrator Map System) app can help you. It will create an zip archive with the map and all the necessary files for it.
You just need to specify the path to the map. And perhaps you also need to specify the path to the game folder where these necessary files for the map are stored.

But as far as I know this application is made only for Windows.

**Comment by PRinceBhai** [comment]
> @PRinceBhai I saw these maps at the address below. Looks like it's a fastdl.
> 
> > I uploaded the map to HTTP
> > http://cs15.noip.cn:29010/

I forgot to mention, I checked before commenting, there aren't any maps that we're missing in that fastdl. Only .wad(s) and .txt(s).

**Comment by Jockey731** [comment]
@Vladislav4KZ
Yes, I canceled my previous account
The maps I provided have been collected since 2002, and some of them can't be found on Google because of their age. So I keep all the map names that haven't changed
I tried to make some graphs before, but because I'm not a professional, there are problems with the waypoints I made, so I can't provide them. Sorry.

**Comment by Jockey731** [comment]
@PRinceBhai
You need to open the maps directory
http://cs15.noip.cn:29010/maps/
If you need a models or sprites, you also need to open the directory
http://cs15.noip.cn:29010/models/
http://cs15.noip.cn:29010/sprites/
Because the home directory only has wad
HTTP here provides download of original map package, It does not include all map downloads, only maps before 2008
http://cs15.noip.cn:29010/CoVerT_WsR_Maps.7z

**Comment by Vladislav4KZ** [comment]
17's buddies is now alive!

**Comment by Jockey731** [comment]
https://all-cs.ru/cs16/maps

**Comment by PRinceBhai** [comment]
@Vladislav4KZ @Jockey731 

Done! 😄

**Comment by Jockey731** [comment]
@PRinceBhai 
Please help upload the following waypoint files

**Comment by PRinceBhai** [comment]
> @PRinceBhai Please help upload the following waypoint files [Waypoint.zip](https://github.com/yapb/graph/files/10110305/Waypoint.zip)

Did you make these? Then you can just use `yb g upload` command.
If not then I'll either have to upload them via a Pull request or download each map then upload them one by one.

**Comment by Jockey731** [comment]
@PRinceBhai
The 10 waypoints I just uploaded were made by others, and the original file is in pwf format
I tried to upload in the game, but it seems that I failed. So please upload, thank you
In addition, I tried to make three waypoint files last year, and would like you to help me check whether there is a problem with the waypoint.

**Comment by PRinceBhai** [comment]
@Jockey731 When converting from pwf to graph format, some graph break or the pwfs are already not properly made. The `yb g save` command allows you to save with check and you can use it to see which waypoints are causing problems or missing.

Also Converting can cause the camp waypoints to get inverted, iirc not sure tho.

The last 3 waypoints you sent have already been uploaded by me on the repo. So you can play with them. I'll check the rest 10 of them and upload them for you. 

Cheers. 👍

**Comment by Jockey731** [comment]
@PRinceBhai 
This waypoint package was sent to me by a friend. Because BOT is all concentrated at the birth point, I did not use it. Please check if there are any missing waypoints that can be used. I didn't upload it because there was a problem with the waypoint
In addition, I want to ask how to know which waypoint files have been updated recently, and whether there are logs to view

**Comment by PRinceBhai** [comment]
@Jockey731 If bots are all concentrated on the spawn points while aiming at the ground or sky then that means the pwf/graph is for a different map with the same name/version.

#1 have the logs for the files that get uploaded to the repo whenever someone uploads. Or if you mean to check if the waypoints have error then you'll have to do them one by one.

> waypoint.zip

I can't find these maps for your graphs in the zip :
de_dust_2003
de_dust_war_cz
de_dust2ct
de_jjojj

de_icac is de_baranayek by Nipper according to this trashed submission at GameBanana?
https://gamebanana.com/mods/380517

**Comment by Jockey731** [comment]
@PRinceBhai 
I don't know. maps were downloaded before. at that time, there were no gamebanana and 17buddies
All maps are placed in this directory
http://cs15.noip.cn:29010/maps/

**Comment by PRinceBhai** [comment]
![29-11-2022_23_17_N6N25njYZ0](https://user-images.githubusercontent.com/39632500/204604705-671745d1-21b5-432d-af7a-5d75c73ea13d.png)
@Jockey731 Can you upload the maps I mentioned except the `dust_2003` here in a zip along with their?
Because as you can see the download on your FastDL is most of the time like this and sometimes ends up failing.

**Comment by Jockey731** [comment]
17buddies There is this map,The map name is correct after checking
In addition to the I mentioned earlier de_aztec2003 and de_dust2_2008 and de_dust2003 and de_inferno2 The existing maps on 17buddies in are not original maps, they just changed their names

**Comment by PRinceBhai** [comment]
Done. 😅

**Comment by Jockey731** [comment]
@PRinceBhai 
Thank you very much for the waypoint documents you made for me. They are very useful

**Comment by Vladislav4KZ** [comment]
It looks like the graph request is completely done, I'm closing the issue.
