### ISSUE TITLE
Create a graph for my ports

### ISSUE THREAD

**Issue by moptex** [yapb/graph#47]
Good afternoon! Please create a graph for my ports. Thank you!

de_genoserv_cz https://gamebanana.com/mods/319446 
de_recoil_cz https://gamebanana.com/mods/377141
de_vessel_cz https://gamebanana.com/mods/366626 

de_dod_anzio https://gamebanana.com/mods/83607 
de_dod_avalanche https://gamebanana.com/mods/83608 
de_dod_caen https://gamebanana.com/mods/290216 
de_dod_charlie https://gamebanana.com/mods/310553 
de_dod_chemille https://gamebanana.com/mods/345148 

de_tfc_avanti https://gamebanana.com/mods/299086 
de_tfc_casbah https://gamebanana.com/mods/300044

**Comment by Drevny13** [comment]
_cz map done, I will continue on the dod maps when have time. I want to say that I do it quickly and as efficiently as possible, but if there are errors or bots behave strangely, I am ready to look at these moments again. On average, I have no more than 2% bug points from the total number of points on the map, usually they are insignificant and do not affect the gameplay

**Comment by PRinceBhai** [comment]
@Vladislav4KZ Every map now has a waypoint. You can close this.
