### ISSUE TITLE
Graph bugs

### ISSUE THREAD

**Issue by dimaspaf14** [yapb/graph#48]
Maps:
de_mirage fixed by @Vladislav4KZ & @overitab theres bug at t-spawn to palace, at the boxes near fence, the bot go stupid right there...

de_inferno fixed by (also same person above) at site a, the bot cant jump from each other tall boxes...

**Comment by Drevny13** [comment]
I didn't notice any obvious bugs on the mirage, but I made anew the place of jumping on the boxes
on inferno yes I saw that there were no jumps up on the boxes
it happens) not always notice this, especially if convert the old ways from the podbot to yapb

**Comment by Vladislav4KZ** [comment]
@Drevny13 Be careful, I noticed wrong paths on de_mirage even when I downloaded the new graph from the zip archive. For example, this path near the boxes going through the fence.
![de_mirage0001](https://user-images.githubusercontent.com/22411953/170869502-1bbe0509-6113-4355-b6ce-5c7b866426dd.png)

**Another wrong path**
![de_mirage0000](https://user-images.githubusercontent.com/22411953/170869602-b2f0f7ce-a402-4af6-bfdc-7c5734620164.png)

**Wrong bidirectional path to the to the tall crate** (must be one-way incoming path from crate to ground)
![de_mirage0004](https://user-images.githubusercontent.com/22411953/170869800-70355aab-7137-48d9-abad-03a721a0588b.png)

**Wrong outgoing path where it's impossible to jump off**
![de_mirage0005](https://user-images.githubusercontent.com/22411953/170869946-767c10aa-3b9f-43cb-98d7-07107c6ff5cf.png)
![de_mirage0006](https://user-images.githubusercontent.com/22411953/170869989-8e5fddd8-eb52-49ca-8089-e681f71abae4.png)

**Wrong outgoing paths near corners (bots will get stuck there)**
![de_mirage0003](https://user-images.githubusercontent.com/22411953/170870068-726898f7-7371-4757-b188-21dfb665c8d5.png)
![de_mirage0007](https://user-images.githubusercontent.com/22411953/170870135-e318c000-a585-4fb0-98f6-de989228f0cd.png)

**Comment by Vladislav4KZ** [comment]
> Maps: de_mirage fixed by @Vladislav4KZ & @Overitab theres bug at t-spawn to palace, at the boxes near fence, the bot go stupid right there...
> 
> de_inferno fixed by (also same person above) at site a, the bot cant jump from each other tall boxes...

I have not fixed graphs for any of these maps. My nickname is in the name of the commit, because this commit contains several graphs that I fixed. I also noticed bugs in graph for de_mirage, but there is no time to fix yet.

**Comment by Drevny13** [comment]
Thank you for the mistakes you noticed. I agree that there should be increased control for standard maps such ways should be as ideal as possible
I don't have time right now to test the ways that i do, even to re-run through the points to look at such errors. But I'm always ready to fix the errors , it's better with screenshots
[graph.zip](https://github.com/yapb/graph/files/8794444/graph.zip)

**Comment by dimaspaf14** [comment]
Here is photo from de_mirage:
![1654350804375-215450870](https://user-images.githubusercontent.com/71385492/172003791-0484c3b1-93d2-422d-bef4-97ecbe2c6cc9.jpg)

The bots just got stuck there & wont move till the round ends, and the bots repeated it again and again (using @Vladislav4KZ nav)

**Comment by Drevny13** [comment]
there no camp points
![image](https://user-images.githubusercontent.com/93672915/172047617-cf410527-c581-469c-b4ff-b3884ba00613.png)
try my graph in archive link above

**Comment by Vladislav4KZ** [comment]
> Thank you for the mistakes you noticed. I agree that there should be increased control for standard maps such ways should be as ideal as possible
> I don't have time right now to test the ways that i do, even to re-run through the points to look at such errors. But I'm always ready to fix the errors , it's better with screenshots
> **[graph.zip](https://github.com/yapb/graph/files/8794444/graph.zip)**

I uploaded the fixed de_mirage.graph to the database (which was uploaded here in a zip archive by Drevny13)
https://github.com/yapb/graph/commit/a7cd9b4b1f416aab3085a344df298fb8de51b508


So you can type in console ``yb g erase iamsure`` and ``yb g load`` to download the fixed graph

**Comment by Vladislav4KZ** [comment]
> > Thank you for the mistakes you noticed. I agree that there should be increased control for standard maps such ways should be as ideal as possible
> > I don't have time right now to test the ways that i do, even to re-run through the points to look at such errors. But I'm always ready to fix the errors , it's better with screenshots
> > **[graph.zip](https://github.com/yapb/graph/files/8794444/graph.zip)**
> 
> I uploaded the fixed de_mirage.graph to the database (which was uploaded here in a zip archive by Drevny13) [a7cd9b4](https://github.com/yapb/graph/commit/a7cd9b4b1f416aab3085a344df298fb8de51b508)

So you can type in console ``yb g erase iamsure`` and ``yb g load`` to download the fixed graph

**Comment by Vladislav4KZ** [comment]
@Drevny13 I also noticed the wrong path on de_inferno graph
![de_inferno0000](https://user-images.githubusercontent.com/22411953/172056021-6a29950f-e07b-4109-8a93-9fc635d4d8ba.png)


### Wrong non-jumping outgoing path to the crate
![de_inferno0001](https://user-images.githubusercontent.com/22411953/172056241-71066f41-6fb6-4649-908e-303c7ea3fe14.png)

**Comment by Drevny13** [comment]
Ok u can fix and upload

**Comment by dimaspaf14** [comment]
the mirage is fixed thanks @Drevny13 
The inferno still got bugs

**Comment by Vladislav4KZ** [comment]
I just uploaded the fixed de_inferno.graph to the database.
