### ISSUE TITLE
graph for dm_blue_paradise map pls

### ISSUE THREAD

**Issue by natashasrcz** [yapb/graph#50]
it is an amazing map and deserves yapb working with it

**Comment by natashasrcz** [comment]
https://www.17buddies.rocks/17b2/View/Map/88796/dm_blue_paradise.html

**Comment by Drevny13** [comment]
I made paths, but could not upload to the database, because of an error that cannot be corrected in the current map due to the inability to get from the bottom platform to the topmost one, it is necessary that from any point you can get to any other. This happens on such maps where there are a lot of teleports and platforms. 
[dm_blue_paradise.zip](https://github.com/yapb/graph/files/8886931/dm_blue_paradise.zip)

**Comment by natashasrcz** [comment]
I will check thx.

So bots cannot use those teleports or elevators on the map?

**Comment by natashasrcz** [comment]
CT bots are killed just after spawn as they seem to spawn at same point on top of the map
attached screenshot
![20220613083536_1](https://user-images.githubusercontent.com/107344829/173293976-19c293a3-a914-41f8-b11f-d072e456b798.jpg)

**Comment by natashasrcz** [comment]
can this be fixed in graph file or I should create custom csdm spawns?

**Comment by Drevny13** [comment]
incorrectly placed spawns are a common mistake on maps, it is better to fix them through the plugin by placing them yourself
by the way, I liked to play against 31 bots on various maps in this way, I play for one team and put 31 bots on another,  placed 31 spawns on both teams

**Comment by Drevny13** [comment]
> So bots cannot use those teleports or elevators on the map?

I tried to bots use teleports and elevators , write it turned out or not

**Comment by natashasrcz** [comment]
ok i added 9 more spawn points for CT as indeed there was just 1 in the map, seems to work fine now

**Comment by natashasrcz** [comment]
https://forums.alliedmods.net/showthread.php?t=43660

**Comment by natashasrcz** [comment]
/* dm_blue_paradise T=10,CT=10 */ Map Spawns Editor Format File
CT 40 -430 -1479 0 355 0
CT -251 -1185 174 0 137 0
T -832 351 168 0 0 0
T 832 -352 168 0 180 0
T -225 -235 40 0 45 0
T 224 232 40 0 222 0
T -576 1222 -1240 0 0 0
T 576 -1156 -1240 0 180 0
T -223 137 -984 0 185 0
T 224 -143 -984 0 0 0
T 1720 236 -1048 0 140 0
T -1656 -240 -1048 0 330 0
CT 0 -256 64 0 0 0
CT 196 1141 174 0 313 0
CT 8 625 -466 0 268 0
CT 488 -600 -722 0 267 0
CT -1419 -1339 -1042 0 92 0
CT 519 873 -1234 0 323 0
CT -902 41 -1234 0 274 0
CT 10 951 -977 0 271 0

**Comment by natashasrcz** [comment]
could you create also for this one https://gamebanana.com/mods/87730 ?

;)

**Comment by Drevny13** [comment]
> could you create also for this one https://gamebanana.com/mods/87730 ?
> 
> ;)

done

**Comment by natashasrcz** [comment]
thank you, it was super fast ;)

**Comment by natashasrcz** [comment]
how about https://gamebanana.com/mods/96547

how would one skip such a map? it is poolday underground and fy_snow at ground

**Comment by natashasrcz** [comment]
thanks for adding gg_snowpool ;)

**Comment by natashasrcz** [comment]
aim_japan_b2 also great map no yapb graph nor pwf to convert from yet

https://gamebanana.com/mods/94626

**Comment by natashasrcz** [comment]
also kind request for graph for fy_alienation map

https://gamebanana.com/mods/85834

**Comment by natashasrcz** [comment]
thank you ;)

**Comment by natashasrcz** [comment]
also please for this fantastic map https://gamebanana.com/mods/82381
csdm_fallout

**Comment by natashasrcz** [comment]
thanks

**Comment by natashasrcz** [comment]
another great ones 
https://gamebanana.com/mods/86304
https://gamebanana.com/mods/86569

fy_iceworld_hd
fy_pool_day_hd

**Comment by natashasrcz** [comment]
thanks

**Comment by natashasrcz** [comment]
dm_snw ???
https://gamebanana.com/mods/82697

**Comment by natashasrcz** [comment]
thanks drevny13

**Comment by natashasrcz** [comment]
I found other excellent maps which deserve yapb:

- [x ] AWP_Egypt_Export_B1: http://80.218.160.72:8082/files/shared/AWP_Egypt_Export_B1.rar
- [x ] AWP_Mansion_Export_B1: http://80.218.160.72:8082/files/shared/AWP_Mansion_Export_B1.rar 
- [x ] AWP_India_Export_B1:  http://80.218.160.72:8082/files/shared/AWP_India_Export_B1.rar 
- [x ] AWP_Tuscan_Export_B1:  http://80.218.160.72:8082/files/shared/AWP_Tuscan_Export_B1.rar
- [x ] awp_35hp_2_w_n_b2: http://80.218.160.72:8082/files/shared/awp_35hp_2_w_n_b2.zip

drevny13 can you take a look?

**Comment by natashasrcz** [comment]
and also AWP_Mountain_Export_B1:  http://80.218.160.72:8082/files/shared/AWP_Mountain_Export_B1.rar

**Comment by natashasrcz** [comment]
+aim_glockon: https://www.17buddies.rocks/17b2/View/Map/10034/aim_glockon.html

**Comment by natashasrcz** [comment]
thanks for AWP_Egypt_Export_B1, did you have chance to see other maps?

**Comment by natashasrcz** [comment]
FYI I created graph for AWP_Mansion_Export_B1, AWP_India_Export_B1, AWP_Tuscan_Export_B1, awp_35hp_2_w_n_b2 would be great if you could check if it is ok as this is my first time

**Comment by Drevny13** [comment]
i see u upload to database, but i cant change file in db . There are no problems with creating paths on fy maps. Just add all possible options for moving the bot. Jumping from heights into the water .Put important point in the middle, a couple of important points for teams and not even necessarily camper points, on small maps the gameplay is more dynamic without camper points
before upload not forget use command yb wp clean all


i use this config
wpt_ypb.cfg

bind "MOUSE1" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 1"
bind "MOUSE2" "yapb menu; menuselect 2; menuselect 2; menuselect 4"
bind "MOUSE5" "yapb menu; menuselect 2; menuselect 2; menuselect 6"
bind "MOUSE4" "yapb menu; menuselect 2; menuselect 2; menuselect 3; menuselect 1"
bind "MOUSE3" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 9"
bind "6" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 6"
bind "7" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 7"

bind "z" "yapb menu; menuselect 2; menuselect 2; menuselect 1"

bind "c" "exec userconfig.cfg"

in
userconfig.cfg
bind "c" "exec wpt_ypb.cfg"

**Comment by natashasrcz** [comment]
i put ct important closer to T side, and t important opposite; map goal in the middle; use only sniper point for real camping localtions, I didnt have problem of jumping into the water; so far they seem to work well (no errors in console)

**Comment by natashasrcz** [comment]
i was trying to follow the manual ;) sometimes had to fix few paths only; tricky is always ladder

**Comment by Vladislav4KZ** [comment]
dm_blue_paradise has already been uploaded into the graph database.

Closed as stale, open a new issue for new requests.
