### ISSUE TITLE
aim_crazyjump bug

### ISSUE THREAD

**Issue by gary00k** [yapb/graph#55]
Hello,
I found a bug on aim_crazyjump map. When bots falls down to water, they stucks there and cannot get back on tower. Could you have a look and fix it? Thank you.

**Comment by Drevny13** [comment]
this map https://gamebanana.com/mods/94122 ?
try this
replace in cstrike\addons\yapb\data\graph
[aim_crazyjump.zip](https://github.com/yapb/graph/files/9484932/aim_crazyjump.zip)

at first I didn't understand about the water, now I looked at the fact that there is water below and you can jump off, I made it possible to jump off and climb up through the teleport, I didn't test with bots, need check

**Comment by gary00k** [comment]
Works, thanks.

**Comment by Vladislav4KZ** [comment]
I do not upload the fixed version of the graph for the reason: why the hell are there nodes floating in the air next to the respawns? And why did you add nodes going down the tower in a spiral, which, in the middle of the path, are connected not by outgoing paths (looking from the tower to the water) but by incoming paths (from the water to the tower)?

**Comment by Drevny13** [comment]
hi, because bots do not know what a teleport is, I have already written that it would be nice to add a teleport start flag and a teleport end flag for waypoints, with the direction of movement where the bot should step into the teleport, so as not to build such crutches
Therefore, I created a fake path for bots that supposedly there is an opportunity to pass. From a height, bots only jump into the water. And the descending paths from the water to the tower are all fake to deceive bots
I do the same on all maps with teleports

**Comment by Vladislav4KZ** [comment]
@Drevny13 Я когда делал вэйпоинты для карт с телепортами, например 35hp_xmas, я ставил точку на телепорте, кэшировал её, создавал точку на пункте телепортации и соединял её входящим путём от кэшированной точки до неё.

Чтобы создать этот путь, ты не должен смотреть на какую либо точку. Иначе ты не сможешь создать путь между кэшированной и ближайшей точкой, и надо выполнить команду создания входящего пути стоя на точке куда должен телепортироваться бот.

И не надо было делать точки парящие в воздухе над башнями. Это лишнее.

**Comment by Vladislav4KZ** [comment]
И я сначала думал что те пути про которые я говорил были сделаны чтобы боты спрыгивали с башни, но со странными путями, где-то двухсторонние, а где-то входящие (снизу-вверх)

**Comment by Vladislav4KZ** [comment]
Надо потом как-нибудь описать создание путей для телепортов в документации.

**Comment by Drevny13** [comment]
как сделать чтобы не телепортироваться при нахождении в телепорте?

**Comment by Vladislav4KZ** [comment]
> как сделать чтобы не телепортироваться при нахождении в телепорте? 

Я создавал две точки перед и за телепортом соединеные между собой (можно двухсторонним путём), но точку созданную за телепортом надо кэшировать чтобы потом создать путь до места телепортации.

**Comment by Vladislav4KZ** [comment]
@Drevny13 Вот примерно оно так должно выглядеть:
![Picsart_22-11-09_21-49-36-570.jpg](https://user-images.githubusercontent.com/22411953/200876649-4a582454-3cc5-4035-b429-0f9c1894d160.jpg)

**Comment by Vladislav4KZ** [comment]
Под кэшированием вэйпоинта я имею ввиду команду ``yb g cache``, оно же в меню называется как "Запомнить вэйпоинт".

Чтобы удалить вэйпоинт из кэша/забыть вэйпоинт, нужно отойти в сторону где нет вэйпоинтов поблизости и выполнить эту команду снова.

**Comment by Vladislav4KZ** [comment]
> Под кэшированием вэйпоинта я имею ввиду команду ``yb g cache``, оно же в меню называется как "Запомнить вэйпоинт".

Чтобы удалить вэйпоинт из кэша/забыть вэйпоинт, нужно отойти в сторону где нет вэйпоинтов поблизости и выполнить эту команду снова.

**Comment by Drevny13** [comment]
хорошо, надо делать так, если у бота нет проблем с такими длинными соединениями

**Comment by PRinceBhai** [comment]
@Vladislav4KZ I think this issue can also be closed.
