### ISSUE TITLE
can someone make a waypoint for me

### ISSUE THREAD

**Issue by TheArtemMaps** [yapb/graph#56]
hi. i'm not good at making waypoints, and i'm asking for somebody to make it for me. map is es_horror link: https://gamebanana.com/mods/98434

**Comment by PRinceBhai** [comment]
Bro, where the fuck is the Escape zone in this map? I've got the whole map waypoint-ed.

**Comment by TheArtemMaps** [comment]
here
![20220915142954_1](https://user-images.githubusercontent.com/91487356/190392730-33d0ae03-4a0a-412e-b252-3c779a441d9d.jpg)

**Comment by PRinceBhai** [comment]
Dude, I still can't find it that area in the map, are you sure that's the correct map that you've shown here?

can you like noclip and show me from above where this place is supposed to be?

**Comment by TheArtemMaps** [comment]
ok, here's a video. 

https://user-images.githubusercontent.com/91487356/190462444-1162c07d-3930-40f5-9ce5-3bff505fa8ca.mp4

**Comment by PRinceBhai** [comment]
Done.

**Comment by TheArtemMaps** [comment]
send it

**Comment by TheArtemMaps** [comment]
oh, nevermind i found it. thank you so so much!
