### ISSUE TITLE
de_dust2_thera B5.graph

### ISSUE THREAD

**Issue by d3nchk** [yapb/graph#61]

**Comment by PRinceBhai** [comment]
Can't find this map aswell there's I only have b3 of dust2_thera.

**Comment by Vladislav4KZ** [comment]
> Can't find this map aswell there's I only have b3 of dust2_thera.

Looks like your Google is broken 😄

Here is the map: https://gamebanana.com/mods/83788 (b3, b4 and b5)

**Comment by PRinceBhai** [comment]
> > Can't find this map aswell there's I only have b3 of dust2_thera.
> 
> Looks like your Google is broken 😄
> 
> Here is the map: https://gamebanana.com/mods/83788 (b3, b4 and b5)

Yup, not a single link that leads to that map on the whole page.
Do you use google or yandex?

![chrome_08-11-2022_22_10_41_KkwHTiqDya](https://user-images.githubusercontent.com/39632500/200623915-1b42db43-c90b-42ea-a0e8-a598eeb85cd5.png)

**Comment by Vladislav4KZ** [comment]
> Do you use google or yandex?

I'm using Google. I wonder how you wrote the search query, and what search engine do you use?

**Comment by Vladislav4KZ** [comment]
![Screenshot_20221108-225227.png](https://user-images.githubusercontent.com/22411953/200626592-5f4e07ef-e625-4b01-809d-631eb7580a52.png)

**Comment by PRinceBhai** [comment]
![08-11-2022_23_01_X2OjQok9qH](https://user-images.githubusercontent.com/39632500/200634844-6c37a6e5-e867-4a5f-9cee-8a621291f70f.png)
Google hates or something I guess.
