### ISSUE TITLE
cs_mtnnl.graph

### ISSUE THREAD

**Issue by d3nchk** [yapb/graph#64]

**Comment by PRinceBhai** [comment]
Yo, I can't find this map. Put a link to it here.

**Comment by Vladislav4KZ** [comment]
> Yo, I can't find this map. Put a link to it here.

@PRinceBhai https://gamebanana.com/mods/92240

I don't know why you couldn't find this map. I found all the maps from the graph requests.

**Comment by PRinceBhai** [comment]
![chrome_08-11-2022_22_12_30_bPz5MHL1nK](https://user-images.githubusercontent.com/39632500/200624298-7bb6dc4d-7ef0-4ac1-9114-e31da7f6efad.png)

Same with this.

> @PRinceBhai https://gamebanana.com/mods/92240
> 
> I don't know why you couldn't find this map. I found all the maps from the graph requests.

**Comment by Vladislav4KZ** [comment]
![Screenshot_20221108-225215.png](https://user-images.githubusercontent.com/22411953/200626715-69765b31-e00c-4d82-91db-60313bb5ea10.png)

**Comment by PRinceBhai** [comment]
I wrote the exact same thing. Is this some kind of setting that needs tweaking in google search?
![chrome_08-11-2022_22_59_56_U3US8RNjQt](https://user-images.githubusercontent.com/39632500/200634504-68285bc6-af2d-4985-abef-be1e5bb1905a.png)

**Comment by Vladislav4KZ** [comment]
> I wrote the exact same thing. Is this some kind of setting that needs tweaking in google search?

I didn't tweak anything in the search settings.

I see in your screenshot that Google corrected your query to "cs mtnl", but there is also a link "Search instead for: cs_mtnnl"

I think if the search does not find maps, then write the name of the map + gamebanana or any other website you know with maps for cs 1.6

For example: cs_mtnnl gamebanana

Or in another way: cs_mtnnl cs 1.6 map


Or as a last resort, try another search engine. If Google in India works strangely.

**Comment by PRinceBhai** [comment]
@Vladislav4KZ You can close this I uploaded the graph yesterday.

**Comment by jeefo** [comment]
maybe create issue templates, requesting people to provide link to the map?

**Comment by Vladislav4KZ** [comment]
> You can close this I uploaded the graph yesterday. 

I just saw that you created a graph for cs_mtnnl_v2, not for cs_mtnnl

**Comment by PRinceBhai** [comment]
> I just saw that you created a graph for cs_mtnnl_v2, not for cs_mtnnl

It's just the updated version of the same map from the same author. So I'd suggest playing the v2 instead of the first one.
