### ISSUE TITLE
Please add waypoints in the following maps. 

### ISSUE THREAD

**Issue by relax6969** [yapb/graph#70]
Please boys, add waypoints in the following maps:

awp_dustguts
awp_aztecarea
awp_dust2
awp_dustworld_india
awp_linkmania
de_pf_dust2

Here are the maps and their files:
https://dox.abv.bg/download?id=d33932a120# <- link

**Comment by relax6969** [comment]
Please boys, add waypoints in the following maps:

awp_dustguts
awp_aztecarea
awp_dust2
awp_dustworld_india
awp_linkmania
de_pf_dust2

Here are the maps and their [files:](url)Please boys, add waypoints in the following maps:

awp_dustguts
awp_aztecarea
awp_dust2
awp_dustworld_india
awp_linkmania
de_pf_dust2

Here are the maps and their files:
https://dox.abv.bg/download?id=d33932a120# - link

**Comment by PRinceBhai** [comment]
@relax6969 All of the maps have waypoints now. Use the attached graph for `awp_dust2` as the one already in repo is for a different map with the same name.
[awp_dust2.zip](https://github.com/yapb/graph/files/10112191/awp_dust2.zip)

**Comment by relax6969** [comment]
Hello PRinceBhai, 
Thanks for the reply, and for making the waypoints for awp_dust2! This is great.
But I don't understand where to search (download) waypoints for the other maps, the rest:
awp_dustguts
awp_aztecarea
awp_dustworld_india
awp_linkmania
de_pf_dust2
Attached plss link, or please - attach a zip file here.
Sorry for my ignorance and bad english but could you give me a link or a zip file.
Thank you very much!

**Comment by PRinceBhai** [comment]
> I don't understand where to search (download) waypoints for the other maps, the rest: awp_dustguts awp_aztecarea awp_dustworld_india awp_linkmania de_pf_dust2

All of these are in the repository now, just load up the map and YApB will automatically download the graphs.

**Comment by relax6969** [comment]
Thanks man! Thank you very much!

**Comment by PRinceBhai** [comment]
> Thanks man! Thank you very much!

Close this issue. 👍

**Comment by relax6969** [comment]
Yes! Thanks!!!

**Comment by PRinceBhai** [comment]
> Yes! Thanks!!!

You need to close this issue, my man. 😆

**Comment by relax6969** [comment]
ok
