### ISSUE TITLE
zm_assault_anthill.graph

### ISSUE THREAD

**Issue by commandcobra7** [yapb/graph#74]

**Comment by Drevny13** [comment]
i see that graph already in database, if u want i can create a new one

**Comment by commandcobra7** [comment]
@Drevny13 I tested the map, it's best to make a new one because waypoints are few and some waypoints are giving errors, it would be better if you create a new waypoint, thanks in advance

**Comment by Drevny13** [comment]
try this

[zm_assault_anthill.zip](https://github.com/yapb/graph/files/11208196/zm_assault_anthill.zip)
