### ISSUE TITLE
cs_assault_snowh.graph

### ISSUE THREAD

**Issue by ghost** [yapb/graph#77]
https://gamebanana.com/mods/429388

**Comment by Drevny13** [comment]
done

**Comment by ghost** [comment]
Thank you for taking your time and realizing the graph, but I see that you uploaded cs_assault_KIEV, although my map is named cs_assault_SNOWH, did you make any error on your end?

EDIT: Sorry, didn't realize that you made for my map and for someone's else map. Thank you!
