### ISSUE TITLE
For zm_4rooms and zm_spartan_dust2 maps Add to bots please.

### ISSUE THREAD

**Issue by cyclone198** [yapb/graph#80]
I want to add bots for these maps. Thank you very much. I need to help you
zm_4rooms : https://gamebanana.com/mods/410177
zm_spartan_dust2:  https://gamebanana.com/mods/89006

**Comment by Drevny13** [comment]
by the way here  is a tutorial how to make your own waypoints
https://yapb.readthedocs.io/en/latest/waypointing.html

I don't like to do for zm maps and not play on zombie servers. 
Maiking ways for zm usually takes 2-3 times more time than for regular de cs scenario
Maybe I 'm doing it too responsibly , but I can 't do it any other way
Therefore, I advise you to try to start doing it yourself, maybe you will like it)

my binds for make ways

bind "MOUSE1" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 1"
bind "MOUSE2" "yapb menu; menuselect 2; menuselect 2; menuselect 4"
bind "MOUSE5" "yapb menu; menuselect 2; menuselect 2; menuselect 6"
bind "MOUSE4" "yapb menu; menuselect 2; menuselect 2; menuselect 3; menuselect 1"
bind "MOUSE3" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 9"
bind "6" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 6"
bind "7" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 7"

**Comment by cyclone198** [comment]
I'm Turkish and my English isn't that good to be able to do that. How can I do it? I really want to do it, of course, but I don't understand anything.

**Comment by Vladislav4KZ** [comment]
Request is done by Ark:
https://github.com/yapb/graph/commit/9e6512ae141a385da6ea15ce67383d94acfcd763
https://github.com/yapb/graph/commit/5f0c522b4279f8dfdf7da643bf32c48dc0830416
