### ISSUE TITLE
YAPBot Graph for cs_italy2

### ISSUE THREAD

**Issue by relax6969** [yapb/graph#81]
Hello,
Could you please create an improved version yapb/graph for cs_italy2 ? 
I found a yapb bot waypoint for cs_italy2 uploaded somewhere, but it 
was very incomplete and the bots were standing like idiots, jumping
 around in one place!  More precisely: all bots born in buildings could
 not or did not know how to get out of them...
I want to say thanks in advance, as well as for the nice craftsmanship of the bots
 themselves. I use them with great pleasure in my server and I am extremely satisfied!

**Comment by relax6969** [comment]
I'm sorry, the topic turned out to be redundant, there are points for the bots uploaded to the site, and they are made great!

**Comment by Vladislav4KZ** [comment]
> there are points for the bots uploaded to the site, and they are made great!

@relax6969 you mean the YaPB Graph Database? Which is the current GitHub repository you are currently in.

If there is a low-quality graph containing errors, etc. then tell us.

If there is a working graph here, then the issue can be closed.

**Comment by Vladislav4KZ** [comment]
As I can see, the previous version of the graph by SoUlFaThEr was made for another map with the same name, which I can't find on the internet.

A year ago, a guy with "PrinceBhai" nickname made a new graph for cs_italy2 by Niklas Olsson, and replaced the previous version with it in our database.
