### ISSUE TITLE
Zm_cpl_human_Base and zm_biohazard_base_mx maps add bots please

### ISSUE THREAD

**Issue by cyclone198** [yapb/graph#82]
Friends, I would be very grateful if you add waypoints to these 2 maps.  

zm_cpl_human_base  link : https://gamebanana.com/mods/88127

zm_biohazard_base_mx link :  https://gamebanana.com/mods/88010

**Comment by MysticDeathProject** [comment]
> Friends, I would be very grateful if you add waypoints to these 2 maps.
> 
> zm_cpl_human_base link : https://gamebanana.com/mods/88127
> 
> zm_biohazard_base_mx link : https://gamebanana.com/mods/88010

I can make but only for project in yapb but I haven't there access for upload from my account github, if I upload from game my authors will be shorts in here

**Comment by Drevny13** [comment]
done
