### ISSUE TITLE
Ts don't plant the bomb on de_train

### ISSUE THREAD

**Issue by mildly-useful** [yapb/graph#86]
I'm using the latest waypoints from here as of 6th April, 2024, and the terrorists don't plant the bomb on de_train. They just roam around the map searching for kills. If someone could fix this that'd be neat.

**Comment by jeefo** [comment]
![image](https://github.com/yapb/graph/assets/1781346/51509df0-2b2a-49cc-a91a-7204e8e3b26c)
can't reproduce, works fine for  me

**Comment by mildly-useful** [comment]
Thanks for replying! That's odd, they did not plant the bomb at all in the 10 mins I tried it (with me playing in their team). I'll try it again and reply back with updates. Maybe it was some temporary bug...? They plant it in other maps, so it's not like I had the option to do objectives disabled. Hmm, weird.

**Comment by mildly-useful** [comment]
I tried it again and it seems they do plant. It was just that during the time I played, they kept trying to plant in the same buggy spot. The bots seem to have issue with this spot specifically (image in link). The bomb carrier moves erratically when he's at that point on top of the train (near the plant marker), or it just spins.

![Screenshot from 2024-04-11 20-10-22](https://github.com/yapb/graph/assets/154385756/15fba06d-1c60-4940-9fb0-bf69fe2aee6b)

**Comment by jeefo** [comment]
try latest build

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mildly-useful** [comment]
I tried the latest version (4.5.1008) and the latest graph files. Then I restarted the rounds so that I can see them try to plant at that train. Out of (about) ten times, I did not see that issue happen again. I suppose it's fixed. Thank you very much for the fast fix! 

I did notice one thing though, the T bomber starting at spawn almost never chooses to go through Ivy, making the bots a bit predictable. The other bots do go through Ivy, but not the bomber. Most of the time, bots just go through mid. Can this be randomized somehow so bots take all paths more equally, especially the bomber bot?

**Comment by mildly-useful** [comment]
![Unsaved Image 1](https://github.com/yapb/graph/assets/154385756/38c3ad58-2186-4a55-a60a-95b77d437139)
Also, I suppose I should mention this, I once saw the CTs unable to defuse the bomb when placed there. They kept fiddling around and going haywire.  

Also, I guess I should close the issue?

**Comment by jeefo** [comment]
Ah, the last fix wasn't correct. Try the latest build once again. About the chosen routes, well, i'm recommend to replace the graph file with the one provided by podbot_mm.

**Comment by mildly-useful** [comment]
I'll try the latest build and play some Train to see how they behave now. I'll report back later!

Btw, how does the podbot_mm graph differ from the yapb graph? I thought the yapb graphs from github are the best. I suppose I could just go and look at both graph files myself, but as someone completely new to CS waypoint editing, I'll also take a quick answer from experienced waypointers, if that's possible. 

Aren't the yapb graphs from github essentially the podbot_mm graphs, but improved?

**Comment by mildly-useful** [comment]
I played a few more rounds and planted the bomb in that same spot. Only one single time the CTs couldn't defuse, though they may have ran out of time. I am not 100% sure, I need to test it some more. In the meantime, I also saw a T getting stuck trying to plant here. It kept going left and right repeatedly. 

![Screenshot from 2024-04-15 01-44-22](https://github.com/yapb/graph/assets/154385756/4cfa13ba-82e7-4ab7-9dbc-555de00bf761)

**Comment by mildly-useful** [comment]
![Screenshot from 2024-04-18 20-02-47](https://github.com/yapb/graph/assets/154385756/c4dcc6ac-ef7c-4ed8-a726-738276334d1e)

I kept playing some more rounds and the CTs seem to be doing alright now, defusing the bomb on that spot. I think the issue is fixed. So, thank you very much. I'd still really like it if the bots took the path to Ivy more often though.
