### ISSUE TITLE
Update waypoints

### ISSUE THREAD

**Issue by MysticDeathProject** [yapb/graph#87]
Привет всем а как добавить обновленный вейпоинт zm_forested с последними исправлениями через yb g upload через cs 1.6 ?

**Comment by Vladislav4KZ** [comment]
Сделай Pull Request или загрузи graph сюда, и я заменю старый граф на новый.

**Comment by MysticDeathProject** [comment]
Приветик вот 
[zm_forested.zip](https://github.com/yapb/graph/files/15052542/zm_forested.zip)
обновленный только он в pwf формате при обновлении в самом yapb он заменился на старую версию и yb_graph_auto_collect_db 0 отключен

**Comment by Vladislav4KZ** [comment]
@MysticDeathProject заменил граф, можешь проверить через пару минут. С базы теперь должна качаться новая версия графа.

**Comment by Vladislav4KZ** [comment]
> обновленный только он в pwf формате при обновлении в самом yapb он заменился на старую версию

Можешь отключить автозагрузку графов с базы, установив пустое значение квара ``yb_graph_url`` в yapb.cfg
Тогда YaPB будет конвертировать PWF вэйпоинт с папки ``addons/yapb/data/pwf`` в Graph формат.

**Comment by MysticDeathProject** [comment]
Хорошо спасибо большое все работает и теперь скачиваеться именно обновленная версия вейпоинта
