### ISSUE TITLE
[request] pls fix de_westtime

### ISSUE THREAD

**Issue by fred0r** [yapb/graph#88]
bots never use roof and often deadlock without moving at all - especially terror in 'left mid', which causes dropping the bomb endlessly.
`mp_afk_bomb_drop_time "5"` and `yb_camping_allowed "0"` are set.

**Comment by MysticDeathProject** [comment]
Only admins can replace this waypoints on github

**Comment by Vladislav4KZ** [comment]
If anyone wants to make or has made a fixed graph, they can create a Pull Request, or attach the graph here, I will upload it to the database.

**Comment by MysticDeathProject** [comment]
> If anyone wants to make or has made a fixed graph, they can create a Pull Request, or attach the graph here, I will upload it to the database.

Приветик я плохо разбираюсь в github я могу создать waypoints с нуля, но нужна твоя помощь, я не знаю как перезалить waypoints если он уже залит в database куда я могу скинуть тебе исправленный вейпоинт и чтобы ты его залил.

**Comment by Vladislav4KZ** [comment]
@MysticDeathProject Я же написал, прикрепи сюда файл, и я заменю старый граф на исправленный.

Можешь .graph файл запаковать в zip архив и прикрепить к сообщению, либо загрузи его в любое удобное для тебя место, и дай ссылку на файл.

**Comment by MysticDeathProject** [comment]
@Vladislav4KZ добавь меня в друзья в дискорд или тг
Дискорд Mysticpawn#2073
Telegram: @alinadevo4ka
И это не реклама я помогу бесплатно и помогу чем смогу

**Comment by MysticDeathProject** [comment]
> @MysticDeathProject Я же написал, прикрепи сюда файл, и я заменю старый граф на исправленный.
> 
> Можешь .graph файл запаковать в zip архив и прикрепить к сообщению, либо загрузи его в любое удобное для тебя место, и дай ссылку на файл.

Хорошо попробую извини в силу неопытности я мало знаю что и как тут в github я попробую

**Comment by Vladislav4KZ** [comment]
@MysticDeathProject кинул заявку а дискорде. Проверяй.

Никнейм: $_Vladislav, имя пользователя: rasstaman1337

**Comment by Vladislav4KZ** [comment]
@fred0r I uploaded the fixed graph by @MysticDeathProject.

To download it, enter the following command line into the in-game console (you must be connected to the internet):
```
yb g erase iamsure
```

Then this line:
```
yb g load
```

After entering these commands, a new graph should be downloaded from the database.

**Comment by fred0r** [comment]
@Vladislav4KZ 
i always pull this repo, which resides undereneath my yapb-install.
THX!
