### ISSUE TITLE
Very Slightly Improved de_foption graph

### ISSUE THREAD

**Issue by TumbleBee6** [yapb/graph#90]
Bots can now use the elevator near CT spawn
![20240929205606_1](https://github.com/user-attachments/assets/1ac324f5-b440-48b3-be0f-94c54508628a)
and the ladder near CT spawn
![20240929205614_1](https://github.com/user-attachments/assets/95221bb0-e21b-42f0-b721-8b71f141570a)

Mediafire: https://www.mediafire.com/file/ozlneitb41bdiuj/de_foption.graph/file
Mega: https://mega.nz/file/lQdDESKS#I6jxZ11eSJBR9yCoWaTfwBAbojAPBHSOTe1ujOfrAF0

**Comment by Vladislav4KZ** [comment]
Thank you! I uploaded your graph to the database.
See commit: https://github.com/yapb/graph/commit/01556b8d9a0ea96218c5ea6c00942ae99767d2c6
